version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 2000
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 2000
      runas: root